/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppSetupRouteImport } from './routes/_app.setup'
import { Route as AppPublishRouteImport } from './routes/_app.publish'
import { Route as AppGeneratorRouteImport } from './routes/_app.generator'
import { Route as AppGenerateRouteImport } from './routes/_app.generate'
import { Route as ApiEtsyCallbackRouteImport } from './routes/api.etsy.callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratorRoute = AppGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => AppRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRoute,
} as any)
const ApiEtsyCallbackRoute = ApiEtsyCallbackRouteImport.update({
  id: '/api/etsy/callback',
  path: '/api/etsy/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof AppGenerateRoute
  '/generator': typeof AppGeneratorRoute
  '/publish': typeof AppPublishRoute
  '/setup': typeof AppSetupRoute
  '/upload': typeof AppUploadRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof AppGenerateRoute
  '/generator': typeof AppGeneratorRoute
  '/publish': typeof AppPublishRoute
  '/setup': typeof AppSetupRoute
  '/upload': typeof AppUploadRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/generate': typeof AppGenerateRoute
  '/_app/generator': typeof AppGeneratorRoute
  '/_app/publish': typeof AppPublishRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/upload': typeof AppUploadRoute
  '/api/etsy/callback': typeof ApiEtsyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/generate'
    | '/generator'
    | '/publish'
    | '/setup'
    | '/upload'
    | '/api/etsy/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/generate'
    | '/generator'
    | '/publish'
    | '/setup'
    | '/upload'
    | '/api/etsy/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/generate'
    | '/_app/generator'
    | '/_app/publish'
    | '/_app/setup'
    | '/_app/upload'
    | '/api/etsy/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiEtsyCallbackRoute: typeof ApiEtsyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publish': {
      id: '/_app/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generator': {
      id: '/_app/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof AppGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generate': {
      id: '/_app/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/etsy/callback': {
      id: '/api/etsy/callback'
      path: '/api/etsy/callback'
      fullPath: '/api/etsy/callback'
      preLoaderRoute: typeof ApiEtsyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppGenerateRoute: typeof AppGenerateRoute
  AppGeneratorRoute: typeof AppGeneratorRoute
  AppPublishRoute: typeof AppPublishRoute
  AppSetupRoute: typeof AppSetupRoute
  AppUploadRoute: typeof AppUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGenerateRoute: AppGenerateRoute,
  AppGeneratorRoute: AppGeneratorRoute,
  AppPublishRoute: AppPublishRoute,
  AppSetupRoute: AppSetupRoute,
  AppUploadRoute: AppUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiEtsyCallbackRoute: ApiEtsyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
